benchopt/benchmark_lasso

.github/workflows/main.yml, solvers/julia_pgd.py
Use the new API from benchopt/benchopt#78 for julia solvers.
=> ENH use JuliaSolver class

solvers/l_bfgs_b.py
=> add solver based on L-BFGS-B in scipy

.github/workflows/main.yml, .gitignore, datasets/boston.py, datasets/finance.py, datasets/simulated.py, objective.py, solvers/blitz.py, solvers/cd.py, solvers/celer.py, solvers/cvxpy.py, solvers/cyanure.py, solvers/glmnet.py, solvers/julia_pgd.py, solvers/l_bfgs_b.py, solvers/lightning.py, solvers/python_pgd.py, solvers/r_pgd.py, solvers/sklearn.py, solvers/statsmodels.py
Adapt the benchmark to cope with the refactoring in benchopt#99
=> Fix benchopt 1.1

.github/workflows/main.yml, solvers/r_pgd.R, solvers/r_pgd.py
Use R for the whole PGD computation
=> Fix BenchOpt issue 52

solvers/cyanure.py, solvers/spams.py
I added spams (lars algorithm for small problem with dense matrices and fista for large ones)
I fixed cyanure.py
=> Fix cyanure + add spams

solvers/modopt_fista.py, solvers/modopt_pogm.py
=> added that modopt solvers do not support sparse data

solvers/blitz.py, solvers/cd.py, solvers/celer.py, solvers/cvxpy.py, solvers/cyanure.py, solvers/glmnet.py, solvers/julia_pgd.py, solvers/l_bfgs_b.py, solvers/lightning.py, solvers/modopt_fista.py, solvers/modopt_pogm.py, solvers/python_pgd.py, solvers/r_pgd.py, solvers/sklearn.py, solvers/spams.py
This is a PR to add the references in the classes Solver 
as follows (e.g. for PGD below):
references = [
'I. Daubechies, M. Defrise and C. De Mol, '
'"An iterative thresholding algorithm for linear inverse problems '
'with a sparsity constraint", Comm. Pure Appl. Math., '
'vol. 57, pp. 1413-1457, no. 11, Wiley Online Library (2004)',
'A. Beck and M. Teboulle, "A fast iterative shrinkage-thresholding '
'algorithm for linear inverse problems", SIAM J. Imaging Sci., '
'vol. 2, no. 1, pp. 183-202 (2009)'
]
=> adding all references

.github/workflows/main.yml, solvers/python_pgd.py
=> use scipy svds for compute_lipschitz_constant

datasets/simulated.py
with the new simulation method it's not slow to generate 10_000 features
=> cosmit simulated dataset

objective.py, solvers/blitz.py, solvers/cd.py, solvers/celer.py, solvers/cvxpy.py, solvers/cyanure.py, solvers/glmnet.py, solvers/julia_pgd.py, solvers/l_bfgs_b.py, solvers/lightning.py, solvers/modopt_fista.py, solvers/modopt_pogm.py, solvers/python_pgd.py, solvers/r_pgd.py, solvers/sklearn.py, solvers/spams.py
Add support for `fit_intercept` in some solvers.
Some are left as easy task for interns :)
=> ENH add support for fit_intercept in lasso

test_config.py
see https://github.com/benchopt/benchopt/pull/252
=> FIX ignore julia solver in tests

objective.py, solvers/skglm.py
The goal of this PR is to add `skglm` to the set of solvers for Lasso.
`skglm` is a fast solver for generalized linear models using working set and Anderson acceleration.
Reference: https://github.com/mathurinm/skglm
=> Add `skglm` solver

.github/workflows/main.yml, datasets/libsvm.py, solvers/glmnet.py
Parameter `INFINITY` has been move in the refactoring benchopt/benchopt#265.
This PR intends to avoid leaving it in `runner.py` while it is not needed anymore.
=> ENH cope with API change

solvers/skglm.py
This PR is to implement a skip function for skglm with intercept == True as it was not done in the initial commit. 
skglm is not supporting intercept == True yet.
=> skglm does not support intercept calculation yet

solvers/lars.py
Still not working (does not converge). Also, need to handle some warnings
=> ENH add solver LARS

solvers/lars.py
=> SOLVER skip sparse X for lars

README.rst, example_config.yml
Addresses #80
Note that config for running small toy dataset only works after merging https://github.com/benchopt/benchopt/pull/362
=> ENH add quickstart tutorial with example_config.yml

.github/workflows/main.yml, solvers/snapml.py
To merge after https://github.com/benchopt/benchopt/pull/386 is merged
=> Public cuda version function in snapml

solvers/modopt_fista.py, solvers/modopt_pogm.py
only the Lipschitz constant computation needs to be changed
=> ENH add sparse support to modopt

solvers/cuml.py, solvers/noncvx_pro.py, solvers/snapml.py
Remove snapml and cuml  and noncvx-pro from #95
(don't know the right citation paper for `glum` though)
=> Add cumln snapml and noncvx-pro references

solvers/noncvx_pro.py
without this equal C is not defined in the check when running
=> fix noncvxpro when n_samples=n_features

solvers/noncvx_pro.py
@Klopfe at least with this I don't get an error, but it is super slow, can you have a look ?
=> FIX noncvx pro for sparse X 

solvers/julia_pgd.jl
This PR optimizes the julia_pgd solver with typing.
=> Type julia_pgd solver
