benchopt/benchmark_lasso

- README.rst
Basically explained how to install `benchopt` from source and how to use the local `-l` option
This partly tackles #5 .
> Readme troubleshooting section for examples

- solvers/modopt_fista.py
- solvers/modopt_pogm.py
These 2 algorithms are implemented in [ModOpt](https://github.com/CEA-COSMIC/ModOpt), where they were intended to solve inverse problems (this is why the notations might seem a bit funny).
The defaults are those from [this paper](https://hal.inria.fr/hal-02298569/document) (that I wrote at the beginning of my thesis so please don't be mean).
I saw that none of the other solvers had docs about what they were implementing (i.e. a citation) or their potential hyperparameters, so I didn't do it for those 2, but happy to do it. Otherwise, all there is to know is inside the ModOpt package.
I still need to check that the conda install method is working.
Should I post some results on boston and simulated datasets here?
> Added 2 algorithms to solve LASSO-like problems: restarting FISTA and POGM'

- solvers/celer.py
currently celer does not run because it is passed max_iter = 0 and does not like it.
> FIX: celer does not support max_iter=0

- solvers/celer.py
It is removed since version 0.6.1 that is now on PyPI (it will be removed in sklearn in 1 or 2 versions too)
should fix the failure in #38
> rm normalize parameter in celer

- solvers/blitz.py
I have the push rights to tbjohns/blitzl1 so we no longer have to pin the install to a particular branch of yours @tomMoral 
In particular I have a ready to merge PR there where I have implemented an iteration strategy in addition to `ŧol`, so it may be nice to keep up to date with the original repo.
> Update blitz source of install to main repo

- solvers/blitz.py
I merged this morning into Blitz master an implementation of `max_iter`.
I think iteration stopping criterion has less non linear effects than tolerance. Let me know what you think.
> Change blitz stopping strategy from tolerance to iteration

- solvers/lightning.py
- test_config.py
It seems that lightning again works with python 3.9
However I need to add cython to its dependencies, as otherwise I get:
```
(test) ➜  lasso git:(xfail_julia) ✗ benchopt install . -s lightning
Installing 'lasso' requirements
Install in the current env 'test'? [y/N]: y
Collecting packages:
- 'leukemia' already available
- 'Simulated' already available
... done
Installing required packages for:
- Lightning
- finance
- libsvm
...Collecting git+https://github.com/scikit-learn-contrib/lightning.git
Cloning https://github.com/scikit-learn-contrib/lightning.git to /tmp/pip-req-build-7gox6ycx
Running command git clone -q https://github.com/scikit-learn-contrib/lightning.git /tmp/pip-req-build-7gox6ycx
Resolved https://github.com/scikit-learn-contrib/lightning.git to commit …
```
> readd lightning to test suite

- datasets/libsvm.py
- objective.py
- solvers/glmnet.py
I added rcv1.binary to the datasets, it seems to work, and quite fast, with the policy of #46 
However on finance I get a huge memory consumption, + 18 Gb:
> ENH: support sparse X for glmnet

- solvers/lightning.py
Before:
After:
I also set the random_state. I think it's overkill for now to expose it.
> set permute=False in lightning to fix convergence

- objective.py
It was done in the Gap Safe paper to have the same dual contraint set when lambda varies, but here it's just simpler to have the regular constraint 
Thus we pick
Also @agramfort note that in the standard Fenchel-Rockafellar duality one has 
and 
instead of the opposite (`theta = y - X @ w`) as is done in the Gap paper.
Of potential interest for @lorentzenchr too
The value of the gap is unchanged in my experiments:
|main|this pr|
|---|---| 
|![image](https://user-images.githubusercontent.com/8993218/158789981-56739ecb-6332-47e5-acce-ab980f840f01.png)|![image](https://user-images.githubusercontent.com/8993218/158790385-01427cb0-0677-4860-8054-94a217717318.png)|
> remove scaling by lambda in gap

- objective.py
Before (alpha_max is too high, alpha_max / 2 is greater than the correct alpha_max hence the sovler doesn't move):
After:
> FIX correct alpha_max when using intercept

- solvers/celer.py
- solvers/skglm.py
- solvers/sklearn.py
sklearn now checks in Lasso.fit() that max_iter is > 0, so the current code breaks for solvers using this method (sklearn, celer, skglm).
Here is a fix for celer. @tomMoral if it LGTY I use it in sklearn and skglm too.
> FIX support n_iter = 0 for celer after sklearn breaking change

- .github/workflows/main.yml
- solvers/snapml.py
- test_config.py
Fixes #83 by adding snapml solver
This solver is not good when intercept is True or with small datasets, but for example with rcv1:
One example of run
> add snapml solver

- solvers/noncvx_pro.py
We want to fix noncvx-pro solver for sparse matrix to reproduce the results obtained in original paper, Smooth Bilevel Programming for Sparse Regularization (Poon and Peyré) on leukemia. For the moment, solver is slow. 
See
in comparison to this
> Fix for noncvx-pro solver on sparse matrix

- solvers/glmnet.py
It doesn't fix the large overhead issue on news20 but that's the way it should be done anyways
> glmnet casting coefficients to np outside of `run`

- solvers/noncvx_pro.py
Converge is obtained by setting LBFGS parameters `g_tol` and `f_tol` to 1e-30 as done in the [original implementation](https://github.com/gpeyre/numerical-tours/blob/master/python/optim_7_noncvx_pro.ipynb).
This change doesn't seem to impact the convergence speed of the solver.
As a side-note, should we discuss the **initialization u0**? Here we set it to the all-ones vector, which gives a considerably different initial cost function value compared to other solvers (initialized at the all-zeros vector)?
> FIX noncvx-pro: use same lbfgs options as in original paper

- solvers/cuml.py
Just found out that we simply need to make the conversion to `cupy` sparse matrix to get it running.
Not tested yet, I will on logreg and let you know if this works well.
> FIX cuML solver working with sparse matrices:

- datasets/meg.py
blitz solver expects a contiguous y and fails otherwise
> FIX make y in meg contiguous

- test_config.py
We have released wheels built with numpy 1.20 for celer 0.7.1, so modopt changing numpy version after celer install should no longer be an issue :crossed_fingers:
> remove modopt test skip

- solvers/cuml.py
After https://github.com/benchopt/benchopt/pull/483,
conda channels are specified with a single colon.
> MNT - fix ``cuml`` solver requirements
